### PR TITLE
Add error handling for faulty notes

### PR DESCRIPTION
**Pull request by dapc11**

### CODE REVIEW

**Comment by Furkanzmc** [comment]
Hey! Thanks for the PR.

Can you describe what a faulty note is?

**Comment by dapc11** [comment]
Sorry, should have included that into the commit message. It was basically a note that I created outside the Zettelkasten workflow, thus forgot adding a proper header to the top of the document.

**Comment by dapc11** [comment]
Yes it did, it was just that the title part (not date) of the heading that was missing.

**Comment by Furkanzmc** [comment]
> Yes it did, it was just that the title part (not date) of the heading that was missing.

In that case I think the node ID should be extracted from the file name, and we should use the first non empty line as the title (Excluding the note id part if it's still there). Returning `nil` and not showing that note doesn't sound right to me.

Would you be willing to make that change?

**Comment by dncnmcdougall** [comment]
In my pull request for #19 (#21) I implemented explicit flags that allow you to specify whether to use the title or the filename (or both) for determining the id. It rases an error if you use both and they don't match.
It does not do what this pull request does and raise an error if it could not extract it from the title.

**Comment by Furkanzmc** [comment]
I think #21 is an appropriate solution to this problem as well. Thank you for the contribution! If the new solution doesn't work for you, we can revisit this idea.

**Pull request closed without merging**
